Repository Ureca-Mini-Project-Team4/Oh-no-its-me, pull requests merged in 2025-05, with the labels that each got.

#82 FEAT: #81 InputField 컴포넌트 구현
  react-app/src/components/InputField/InputField.tsx
  react-app/src/components/InputField/InputField.types.ts
Labels: ✨ Feature

#96 FEAT: #83 Redux 전역 상태관리 초기 설정 및 로그인 API 모듈화
  react-app/package-lock.json
  react-app/package.json
  react-app/src/App.tsx
  react-app/src/apis/axiosInstance.ts
  react-app/src/apis/user/login.ts
  react-app/src/hook/useAuth.ts
  react-app/src/pages/Home.tsx
  react-app/src/pages/Login.tsx
  react-app/src/routes.tsx
  react-app/src/store/index.ts
  react-app/src/store/slices/authSlice.ts
  react-app/src/store/slices/pageSlice.ts
  react-app/src/store/slices/timerSlice.ts
  react-app/src/store/store.ts
  react-app/vite.config.ts
Labels: 📬 API, ✨ Feature

#84 FEAT: #80 버튼 컴포넌트 만들기
  react-app/src/components/Button/Button.tsx
  react-app/src/components/Button/Button.types.ts
Labels: ✨ Feature

#86 FEAT: #85 Candidate 반응형 컴포넌트 구현
  react-app/src/components/candidate/Candidate.tsx
  react-app/src/components/candidate/Candidate.types.ts
  react-app/src/styles/index.css
Labels: ✨ Feature

#94 FEAT: #93 Profile Comment 제작
  react-app/src/components/Comment/Comment.tsx
  react-app/src/components/Profile/Profile.tsx
Labels: ✨ Feature

#88 FEAT: #87 WinnerCard 컴포넌트 구현 및 플립 기능 구현
  react-app/package-lock.json
  react-app/package.json
  react-app/src/components/WinnerCard/WinnerCard.tsx
Labels: ✨ Feature

#98 FEAT: #91 Winner 반응형 컴포넌트 구현
  react-app/public/assets/images/people/이시현.png
  react-app/public/assets/images/people/이예슬.png
  react-app/src/App.tsx
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/components/Candidate/Candidate.types.ts
  react-app/src/components/Winner/Winner.tsx
  react-app/src/components/Winner/Winner.types.ts
Labels: ✨ Feature

#105 [REFACT] #104 candidate(백엔드) 수정
  springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java
  springboot-app/src/main/resources/mapper/candidates.xml
Labels: 🔨 Refactor

#106 FEAT: Candidate 백엔드 수정
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java
  springboot-app/src/main/resources/mapper/candidates.xml
Labels: 🔨 Refactor

#107 FEAT: Toast 컴포넌트 구현
  react-app/src/components/Layout/Layout.tsx
  react-app/src/components/Toast/Toast.tsx
  react-app/src/hook/useToast.ts
  react-app/src/pages/Home.tsx
  react-app/src/routes.tsx
  react-app/src/store/index.ts
  react-app/src/store/slices/toastSlice.ts
  react-app/src/styles/index.css
Labels: ✨ Feature

#109 FEAT: #108 Comment 수정 및 import react 제거
  react-app/src/components/Comment/Comment.tsx
  react-app/src/components/Comment/Dropdown.tsx
  react-app/src/components/Winner/Winner.tsx
Labels: 🔨 Refactor

#121 REFACTOR: #120 비밀번호 변경 수정
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java
Labels: 🔨 Refactor

#112 FEAT: 인증 상태 로직 관리 수정 및 User API 모듈화
  react-app/src/apis/axiosInstance.ts
  react-app/src/apis/user/changePassword.ts
  react-app/src/apis/user/getUserInfo.ts
  react-app/src/apis/user/login.ts
  react-app/src/hook/useAuth.ts
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Home.tsx
  react-app/src/pages/Login.tsx
  react-app/src/routes.tsx
  react-app/src/store/index.ts
  react-app/src/store/slices/authSlice.ts
Labels: 📬 API

#119 FEAT: #118 voteAPI 추가
  react-app/src/apis/vote/getVoteResult.ts
  react-app/src/apis/vote/getVoteResultByPollId.ts
  react-app/src/apis/vote/updateVoteCount.ts
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
Labels: ✨ Feature

#125 Feature/api poll
  react-app/src/apis/candidate/postCandidate.ts
  react-app/src/apis/poll/getPoll.ts
  react-app/src/routes.tsx
Labels: 📬 API, ✨ Feature

#124 FEAT: #115 Candidate API 모듈화
  react-app/src/apis/candidate/postCandidate.ts
Labels: ✨ Feature

#129 FIX: 비밀번호 변경 API 유효성 로직 강화
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dto/User.java
Labels: 📬 API, 🐞 BugFix

#130 FEAT: 컨페티 컴포넌트, 에러 바운더리 페이지,라우팅 파일 설정
  react-app/package-lock.json
  react-app/package.json
  react-app/public/assets/images/bg-m.png
  react-app/public/assets/images/bg.svg
  react-app/src/components/Confetti/Confetti.tsx
  react-app/src/pages/ErrorBoundary.tsx
  react-app/src/pages/Main.tsx
  react-app/src/pages/Result.tsx
  react-app/src/routes.tsx
Labels: ✨ Feature, dependencies

#131 FEAT: #123 로딩 컴포넌트 만들기
  react-app/public/assets/icons/spinnergif.gif
  react-app/src/components/Loading/Loading.tsx
Labels: ✨ Feature

#136 FEAT: #135 vote에서 icon 받아올 수 있도록 수정
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/resources/mapper/vote.xml
Labels: 🔨 Refactor

#141 FEAT: Home 페이지 만들기
  react-app/public/assets/images/bg-m.png
  react-app/public/assets/images/bg.svg
  react-app/public/assets/images/main1.png
  react-app/public/assets/images/main2.png
  react-app/public/assets/images/main3.png
  react-app/public/assets/images/main4.png
  react-app/public/assets/images/mockup.png
  react-app/src/hook/useIsMobile.ts
  react-app/src/pages/Home.tsx
  react-app/src/pages/Result.tsx
Labels: 🎨 Html&css, ✨ Feature

#140 FEAT: #139 타이머 구현
  react-app/src/apis/axiosInstance.ts
  react-app/src/apis/poll/getPoll.ts
  react-app/src/hook/useAuth.ts
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Login.tsx
  react-app/src/pages/Main.tsx
Labels: ✨ Feature

#143 FEAT: #142 로그인 예외 처리 수정
  react-app/src/apis/axiosInstance.ts
  react-app/src/hook/useAuth.ts
  react-app/src/pages/ChangePW.tsx
Labels: 🔨 Refactor

#145 FEAT: #144 poll-latest 추가
  springboot-app/src/main/java/com/uplus/eureka/poll/controller/PollController.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/dao/PollDao.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollService.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollServiceImp.java
  springboot-app/src/main/resources/mapper/poll.xml
Labels: ✨ Feature

#148 FEAT: #147 candidate 및 poll 수정
  springboot-app/src/main/java/com/uplus/eureka/SpringBootTestApplication.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java
  springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java
  springboot-app/src/main/resources/mapper/candidates.xml
Labels: ✨ Feature

#151 FEAT: #147 poll candidate api 수정
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java
  springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java
  springboot-app/src/main/resources/mapper/candidates.xml
Labels: ✨ Feature

#153 FEAT: #152 Feature/candidate group
  react-app/src/apis/candidate/getCandidateLatest.ts
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/components/Candidate/Candidate.types.ts
  react-app/src/components/Candidate/CandidateGroup.tsx
Labels: ✨ Feature

#162 FIX: Index.css font 수정
  react-app/src/apis/poll/getPollLatest.ts
  react-app/src/apis/vote/getVoteResultByPollId.ts
  react-app/src/pages/Comment.tsx
  react-app/src/styles/index.css
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/Comment.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentRequest.java
  springboot-app/src/main/resources/mapper/comments.xml
Labels: 🐞 BugFix

#165 FIX: 필요없는 API 모듈 제거 및 메인 페이지에서 제거
  react-app/src/apis/candidate/postCandidate.ts
  react-app/src/apis/poll/getPoll.ts
  react-app/src/pages/Main.tsx
Labels: 📬 API

#166 FEAT: 댓글 목록 조회 및 빈 상태 처리
  react-app/public/assets/images/seal-chat-big.png
  react-app/src/apis/comment/getComment.ts
  react-app/src/components/Character/Character.tsx
  react-app/src/components/Comment/Comment.tsx
  react-app/src/pages/Comment.tsx
Labels: ✨ Feature

#167 FIX: #164 Comment - 타입 에러 해결
  react-app/src/pages/Comment.tsx
Labels: 🐞 BugFix

#174 FIX: candidate dto에 candidateId 추가하기
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
Labels: ✨ Feature

#172 FEAT: #168 결과 확인, 댓글 반응형 CSS 구현
  react-app/src/apis/poll/getPoll.ts
  react-app/src/components/Comment/Comment.tsx
  react-app/src/components/Comment/CommentInputField.tsx
  react-app/src/components/WinnerCard/WinnerCard.tsx
  react-app/src/pages/Comment.tsx
  react-app/src/styles/index.css
Labels: ✨ Feature

#176 FEAT: Vote 페이지 만들기
  react-app/public/assets/images/question/island.svg
  react-app/src/apis/candidate/getCandidateLatest.ts
  react-app/src/apis/vote/postVoteResult.ts
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/components/Candidate/Candidate.types.ts
  react-app/src/components/Candidate/CandidateGroup.tsx
  react-app/src/pages/Vote.tsx
Labels: ✨ Feature

#179 REFACT: #178 한국시간으로 조정
  springboot-app/src/main/java/com/uplus/eureka/candidate/scheduler/CandidateScheduler.java
  springboot-app/src/main/java/com/uplus/eureka/poll/scheduler/PollScheduler.java
Labels: 🔨 Refactor

#183 REFACTOR: #182 랭킹 페이지 useQuery로 리팩토링
  react-app/src/hook/useVoteResults.ts
  react-app/src/pages/Result.tsx
Labels: 📬 API, ✨ Feature

#185 FEAT: #181 로컬에 voted 저장하기
  react-app/src/hook/useAuth.ts
  react-app/src/pages/Main.tsx
  react-app/src/pages/Vote.tsx
Labels: ✨ Feature

#190 REFACTOR: #189 비밀번호 API 요청 바디에 username 필드 추가
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dto/PasswordUpdateRequest.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserService.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java
  springboot-app/src/main/resources/mapper/users.xml
Labels: 🔨 Refactor

#193 [FEAT] #192 로그인 페이지 및 비밀번호 변경 페이지 제작
  react-app/package-lock.json
  react-app/package.json
  react-app/public/assets/images/seal-change-password.png
  react-app/public/assets/images/vector.png
  react-app/src/apis/user/changePassword.ts
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Login.tsx
Labels: ✨ Feature

#195 REFACT: #192 사진 경로 변경
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Login.tsx
Labels: 🔨 Refactor

#198 FEAT: #197 이미지 경로 변경 및 자동으로 isVoted가 모두 초기화 되도록 추가
  react-app/src/pages/ChangePW.tsx
  springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/java/com/uplus/eureka/vote/scheduler/VoteScheduler.java
  springboot-app/src/main/resources/mapper/vote.xml
Labels: ✨ Feature

#200 FEAT: Comment 댓글 수정 삭제
  react-app/src/components/Comment/Comment.tsx
  react-app/src/components/Comment/CommentInputField.tsx
  react-app/src/components/Comment/Dropdown.tsx
  react-app/src/components/Modal/Modal.tsx
  react-app/src/components/Modal/Modal.types.ts
  react-app/src/pages/Comment.tsx
  react-app/src/pages/Vote.tsx
Labels: ✨ Feature

#201 [FEAT] Vote 페이지 수정
  react-app/public/assets/icons/spinnergif.gif
  react-app/src/components/Loading/Loading.tsx
  react-app/src/pages/Vote.tsx
Labels: ✨ Feature

#205 [FEAT] 질문 아이콘 추가 및 css 변경
  react-app/public/assets/images/question/airplane.png
  react-app/public/assets/images/question/alcohol.png
  react-app/public/assets/images/question/celebrity.svg
  react-app/public/assets/images/question/chat.svg
  react-app/public/assets/images/question/cry.svg
  react-app/public/assets/images/question/fashion.svg
  react-app/public/assets/images/question/flight.svg
  react-app/public/assets/images/question/game.svg
  react-app/public/assets/images/question/ghost.svg
  react-app/public/assets/images/question/island.png
  react-app/public/assets/images/question/late.svg
  react-app/public/assets/images/question/lemon.png
  react-app/public/assets/images/question/lottery.svg
  react-app/public/assets/images/question/love.svg
  react-app/public/assets/images/question/oops.svg
  react-app/public/assets/images/question/party.svg
  react-app/public/assets/images/question/sleepy.svg
  react-app/public/assets/images/question/smartphone.svg
  react-app/public/assets/images/question/snack.svg
  react-app/public/assets/images/question/sports.svg
  react-app/public/assets/images/question/talker.svg
  react-app/public/assets/images/question/timemachine.svg
  react-app/public/assets/images/question/youtube.svg
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/components/WinnerCard/WinnerCard.tsx
  react-app/src/pages/Vote.tsx
Labels: 🔨 Refactor

#204 REFACT: #203 로그인, 비밀번호 변경 페이지 REACT QUERY로 변경
  react-app/src/hook/useAuth.ts
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Login.tsx
  springboot-app/src/main/java/com/uplus/eureka/util/JwtUtil.java
Labels: 🔨 Refactor

#208 FEAT: Comment CSS 정리 및 Loading 전체 통일
  react-app/src/pages/Comment.tsx
  react-app/src/pages/Result.tsx
Labels: 🔨 Refactor

#210 REFACTOR: #194 랭킹 페이지 수정
  react-app/public/assets/icons/arrow-right.png
  react-app/public/assets/icons/arrow-right.svg
  react-app/src/components/Winner/Winner.tsx
  react-app/src/constants/iconPath.ts
  react-app/src/constants/imagePath.ts
  react-app/src/pages/Result.tsx
Labels: 🔨 Refactor

#214 REFACTOR: #211 모든 이미지 경로 상수 파일로 리팩토링
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/components/Comment/CommentInputField.tsx
  react-app/src/components/Loading/Loading.tsx
  react-app/src/components/Profile/Profile.tsx
  react-app/src/components/Toast/Toast.tsx
  react-app/src/components/WinnerCard/WinnerCard.tsx
  react-app/src/constants/iconPath.ts
  react-app/src/constants/imagePath.ts
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Comment.tsx
  react-app/src/pages/Home.tsx
  react-app/src/pages/Login.tsx
  react-app/src/pages/Result.tsx
  react-app/src/pages/Vote.tsx
Labels: 🔨 Refactor

#218 [FEAT] Header 컴포넌트 및 로그아웃 모달 구현
  react-app/public/assets/icons/home.png
  react-app/public/assets/icons/logout.png
  react-app/public/logo/favicon.svg
  react-app/src/apis/user/login.ts
  react-app/src/components/Header/Header.tsx
  react-app/src/components/Layout/Layout.tsx
  react-app/src/components/Modal/Modal.tsx
  react-app/src/constants/iconPath.ts
  react-app/src/hook/useLogin.ts
  react-app/src/pages/ChangePW.tsx
  react-app/src/pages/Login.tsx
  react-app/src/pages/Main.tsx
  react-app/src/styles/index.css
Labels: ✨ Feature

#219 FEAT: #215 NotFound 페이지 구현
  react-app/public/assets/images/404.svg
  react-app/src/constants/imagePath.ts
  react-app/src/pages/NotFound.tsx
Labels: ✨ Feature

#227 FIX: #209 로그인 404 에러 수정
  springboot-app/src/main/java/com/uplus/eureka/config/WebMvcConfiguration.java
  springboot-app/src/main/java/com/uplus/eureka/interceptor/JWTInterceptor.java
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/util/JwtUtil.java
Labels: 📬 API

#226 REFACTOR: #221 새로운 동물 이미지로 바꾼다
  react-app/public/assets/images/animal/둥실둥실 떠가는 해파리.jpg
  react-app/public/assets/images/animal/둥실둥실 떠가는 해파리.png
  react-app/public/assets/images/animal/반짝이는 날아다니는 뱁새.jpg
  react-app/public/assets/images/animal/반짝이는 날아다니는 뱁새.png
  react-app/public/assets/images/animal/반짝이는 수영하는 흰수염고래.jpg
  react-app/public/assets/images/animal/방긋방긋 웃는 고양이.jpg
  react-app/public/assets/images/animal/방긋방긋 웃는 고양이.png
  react-app/public/assets/images/animal/방긋방긋 웃는 코알라.jpg
  react-app/public/assets/images/animal/방긋방긋 웃는 코알라.png
  react-app/public/assets/images/animal/부드럽게 움직이는 황금도토리.jpg
  react-app/public/assets/images/animal/부드럽게 움직이는 황금도토리.png
  react-app/public/assets/images/animal/부지런히 일하는 오랑우탄.jpg
  react-app/public/assets/images/animal/부지런히 일하는 토끼.png
  react-app/public/assets/images/animal/빛나는 날아다니는 벌새.jpg
  react-app/public/assets/images/animal/빛나는 날아다니는 벌새.png
  react-app/public/assets/images/animal/빛나는 별처럼 반짝이는 펭귄.jpg
  react-app/public/assets/images/animal/빛나는 별처럼 반짝이는 펭귄.png
  react-app/public/assets/images/animal/사뿐사뿐 걷는 기린.jpg
  react-app/public/assets/images/animal/사뿐사뿐 걷는 기린.png
  react-app/public/assets/images/animal/살금살금 다가가는 악어.jpg
  react-app/public/assets/images/animal/살금살금 다가가는 악어.png
  react-app/public/assets/images/animal/살금살금 다가가는 여우.jpg
  react-app/public/assets/images/animal/살랑살랑 춤추는 아르마딜로.jpg
  react-app/public/assets/images/animal/살랑살랑 춤추는 아르마딜로.png
  react-app/public/assets/images/animal/소곤소곤 이야기하는 여우.jpg
  react-app/public/assets/images/animal/소곤소곤 이야기하는 여우.png
  react-app/public/assets/images/animal/신나게 노래하는 황조롱이.jpg
  react-app/public/assets/images/animal/신나게 노래하는 황조롱이.png
  react-app/public/assets/images/animal/신나게 뛰는 너구리.jpg
  react-app/public/assets/images/animal/신나게 뛰는 너구리.png
  react-app/public/assets/images/animal/어슬렁어슬렁 걷는 코끼리.jpg
  react-app/public/assets/images/animal/어슬렁어슬렁 걷는 코끼리.png
  react-app/public/assets/images/animal/어질어질 나는 타조.jpg
  react-app/public/assets/images/animal/어질어질 나는 타조.png
  react-app/public/assets/images/animal/어질어질 떠다니는 고래.jpg
  react-app/public/assets/images/animal/어질어질 떠다니는 고래.png
  react-app/public/assets/images/animal/우당탕탕 용감한 호랑이.png
  react-app/public/assets/images/animal/우르르 쾅쾅 걷는 하마.jpg
  react-app/public/assets/images/animal/조용히 기어가는 카멜레온.jpg
  react-app/public/assets/images/animal/조용히 기어가는 카멜레온.png
  react-app/public/assets/images/animal/쫄랑쫄랑 뛰어가는 강아지.png
  react-app/public/assets/images/animal/찰칵찰칵 찍는 앵무새.jpg
  react-app/public/assets/images/animal/찰칵찰칵 찍는 앵무새.png
  react-app/public/assets/images/animal/쿵쿵 뛰는 바다사자.jpg
  react-app/public/assets/images/animal/쿵쿵 뛰는 바다사자.png
  react-app/public/assets/images/animal/쿵쿵 뛰는 오리 아이콘.png
  react-app/public/assets/images/animal/쿵쿵 뛰는 오리.jpg
  react-app/public/assets/images/animal/팔랑팔랑 날리는 푸른머리오리.jpg
  react-app/public/assets/images/animal/팔랑팔랑 날리는 푸른머리오리.png
  react-app/public/assets/images/animal/펄럭펄럭 뛰는 다람쥐.jpg
  react-app/public/assets/images/animal/펄럭펄럭 뛰는 다람쥐.png
  react-app/public/assets/images/animal/푸드덕 푸드덕 뛰는 하이에나.jpg
  react-app/public/assets/images/animal/푸드덕 푸드덕 뛰는 하이에나.png
  react-app/public/assets/images/animal/후다닥 달리는 마카크.jpg
  react-app/public/assets/images/animal/후다닥 달리는 마카크.png
  react-app/public/assets/images/animal/휘청휘청 놀란 사자.png
  react-app/public/assets/images/animal/희죽희죽 웃는 판다.jpg
  react-app/public/assets/images/animal/희죽희죽 웃는 판다.png
  react-app/src/constants/imagePath.ts
Labels: 🔨 Refactor

#223 REFACTOR: #213 물개 변경
  react-app/public/assets/images/seal-change-password.png
  react-app/public/assets/images/seal-change-password.svg
  react-app/public/assets/images/seal-chat-big.png
  react-app/public/assets/images/seal-chat-big.svg
  react-app/src/components/Character/Character.tsx
  react-app/src/constants/imagePath.ts
  react-app/src/pages/ChangePW.tsx
Labels: 🔨 Refactor

#220 REFACTOR: #217 Vote 페이지 리팩토링
  react-app/src/components/Candidate/CandidateGroup.tsx
  react-app/src/hook/useVote.ts
  react-app/src/hook/useVoteData.ts
  react-app/src/hook/useVoteSubmit.ts
  react-app/src/pages/Vote.tsx
Labels: 🔨 Refactor

#235 [REFACTOR] #234 반응형 페이지 추가
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/components/Winner/Winner.tsx
  react-app/src/pages/Result.tsx
  react-app/src/pages/Vote.tsx
Labels: 🔨 Refactor

#239 REFACTOR: #238 favicon 변경
  react-app/index.html
  react-app/public/favicon-16x16.png
  react-app/public/favicon-32x32.png
  react-app/public/favicon.ico
Labels: 🔨 Refactor

#242 REFACTOR: #240 vote 페이지 수정
  react-app/src/components/Candidate/Candidate.tsx
  react-app/src/pages/Vote.tsx
Labels: 🔨 Refactor

#237 REFACTOR: #236 랭킹 페이지 새로고침 전체 div에 적용
  react-app/src/pages/Result.tsx
Labels: 🐞 BugFix

#245 REFACTOR: #222 useIsMobile 훅 제거 및 useMediaQuery로 변경
  react-app/src/hook/useIsMobile.ts
  react-app/src/pages/Comment.tsx
  react-app/src/pages/Home.tsx
Labels: 🔨 Refactor
