Repository Ureca-Mini-Project-Team4/Oh-no-its-me, pull requests merged in 2025-03, with the labels that each got.

#2 DOCS: 이슈 템플릿 및 풀 리퀘스트 템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#13 FEAT: #11 Vote API 특정 투표 결과 조회
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/Vote.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteException.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteRequset.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/resources/application.properties
  springboot-app/src/main/resources/mapper/vote.xml
Labels: 📬 API, ✨ Feature

#12 FEAT: #3 User API 로그인 및 정보 확인
  .gitignore
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dao/UserDao.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dto/LoginRequest.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dto/User.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserService.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java
  springboot-app/src/main/resources/mapper/users.xml
Labels: ✨ Feature

#17 Feature: candidate and poll api 구현
  README.md
  springboot-app/build.gradle
  springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateServiceImp.java
  springboot-app/src/main/java/com/uplus/eureka/poll/controller/PollController.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/dao/PollDao.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/dto/Question.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollService.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollServiceImp.java
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java
  springboot-app/src/main/resources/application.properties.template
  springboot-app/src/main/resources/mapper/candidates.xml
  springboot-app/src/main/resources/mapper/poll.xml
Labels: ✨ Feature

#21 Fix/user
  .settings/org.eclipse.buildship.core.prefs
  springboot-app/src/main/java/com/uplus/eureka/user/model/dao/UserDao.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/service/UserServiceImp.java
  springboot-app/src/main/resources/application.properties.template
Labels: 🔨 Refactor

#31 FEAT: #30 Swagger 초기 설정 + User API 문서화
  .settings/org.eclipse.buildship.core.prefs
  README.md
  springboot-app/src/main/java/com/uplus/eureka/ExceptionControllerAdvice.java
  springboot-app/src/main/java/com/uplus/eureka/config/SwaggerConfiguration.java
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dto/PasswordUpdateRequest.java
  springboot-app/src/main/resources/static/assets/img/logo.png
Labels: 📬 API, ✨ Feature

#32 FEAT: #27 투표 완료 등록 api
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/resources/mapper/vote.xml
Labels: 📬 API, ✨ Feature

#36 FEAT: #34 vote swagger 문서화
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteRequest.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
Labels: ✨ Feature

#29 FEAT: #23 Feature/comment getAllComments, getCommentById 완성
  springboot-app/src/main/java/com/uplus/eureka/comment/controller/CommentController.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dao/CommentDao.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/Comment.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentRequest.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentUpdateRequest.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/exception/CommentException.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/exception/GlobalExceptionHandler.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/service/CommentService.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/service/CommentServiceImp.java
  springboot-app/src/main/resources/application.properties
  springboot-app/src/main/resources/mapper/comments.xml
Labels: ✨ Feature

#39 Develop
  springboot-app/src/main/java/com/uplus/eureka/ExceptionControllerAdvice.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/CandidateNotFoundException.java
  springboot-app/src/main/java/com/uplus/eureka/comment/controller/CommentController.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dao/CommentDao.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/Comment.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentRequest.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentUpdateRequest.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/exception/CommentException.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/exception/GlobalExceptionHandler.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/service/CommentService.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/service/CommentServiceImp.java
  springboot-app/src/main/java/com/uplus/eureka/config/SwaggerConfiguration.java
  springboot-app/src/main/java/com/uplus/eureka/poll/controller/PollController.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/dto/PollServiceException.java
  springboot-app/src/main/java/com/uplus/eureka/user/controller/UserController.java
  springboot-app/src/main/java/com/uplus/eureka/user/model/dto/PasswordUpdateRequest.java
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dao/VoteDao.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteRequest.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteResult.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteService.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/resources/application.properties
  springboot-app/src/main/resources/mapper/comments.xml
  springboot-app/src/main/resources/mapper/vote.xml
  springboot-app/src/main/resources/static/assets/img/logo.png
Labels: ✨ Feature

#38 Feature/comment
  springboot-app/src/main/java/com/uplus/eureka/comment/controller/CommentController.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dao/CommentDao.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/Comment.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentRequest.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/CommentUpdateRequest.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/exception/CommentException.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/exception/GlobalExceptionHandler.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/service/CommentService.java
  springboot-app/src/main/java/com/uplus/eureka/comment/model/service/CommentServiceImp.java
  springboot-app/src/main/resources/application.properties
  springboot-app/src/main/resources/mapper/comments.xml
Labels: ✨ Feature

#54 BUG: Comment - JsonProperties annotation 중복 충동
  springboot-app/src/main/java/com/uplus/eureka/comment/model/dto/Comment.java
Labels: 🐞 BugFix

#53 FEAT: #52 예외처리 수정
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/dto/VoteException.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/exception/GlobalExceptionHandler.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/exception/VoteException.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/resources/application.properties
Labels: ✨ Feature

#57 Feature/poll-revise 수정
  springboot-app/src/main/java/com/uplus/eureka/candidate/controller/CandidateController.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dao/CandidateDao.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/dto/Candidate.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateService.java
  springboot-app/src/main/java/com/uplus/eureka/candidate/model/service/CandidateServiceImp.java
  springboot-app/src/main/java/com/uplus/eureka/config/MyBatisConfig.java
  springboot-app/src/main/java/com/uplus/eureka/poll/controller/PollController.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/dao/PollDao.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/dto/Question.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollService.java
  springboot-app/src/main/java/com/uplus/eureka/poll/model/service/PollServiceImp.java
  springboot-app/src/main/resources/mapper/candidates.xml
  springboot-app/src/main/resources/mapper/poll.xml
Labels: ✨ Feature

#63 DEBUG: #62 vote 예외처리 수정
  springboot-app/src/main/java/com/uplus/eureka/vote/contoller/VoteController.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/exception/GlobalExceptionHandler.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/exception/VoteException.java
  springboot-app/src/main/java/com/uplus/eureka/vote/model/service/VoteServiceImp.java
  springboot-app/src/main/resources/mapper/vote.xml
Labels: 🐞 BugFix

#67 DEPLOY: #66 Docker + Github Action CI/CD
  .github/workflows/backend-cicd.yml
  README.md
  springboot-app/Dockerrun.aws.json
  springboot-app/dockerfile
  springboot-app/src/main/resources/application.properties
Labels: 📃 Docs, 🌏 Deploy
